apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my1st-app
  namespace: argocd
  finalizers: []
spec:
  destination:
    name: in-cluster
    namespace: broesel
  source:
    path: abc
    repoURL: https://xxx.yy
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
